CRM_Upack_kz/Models/Application.cs
using System;
using CRM_Upack_kz.Enums;

namespace CRM_Upack_kz.Models
{
    public class Application
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string ManagerId { get; set; }
        public virtual User Manager { get; set; }
        public string ClientId { get; set; }
        public virtual Client Client { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime WaitingDate { get; set; }
        public string ArticleNumber { get; set; }
        public decimal Quantity { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public string Comment { get; set; }
        public decimal NumberApplication { get; set; }
        public AppState AppState { get; set; } = AppState.Новая;
    }
}

CRM_Upack_kz/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CRM_Upack_kz.Enums;
using CRM_Upack_kz.Models;
using CRM_Upack_kz.Services;
using CRM_Upack_kz.ViewModels;
using CRM_Upack_kz.ViewModels;
using ExcelLibrary.BinaryFileFormat;
using ExcelLibrary.SpreadSheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using NLog;
using WebStudio.Services;
using X.PagedList;


namespace CRM_Upack_kz.Controllers
{
    [Authorize]
    public class ApplicationsController : Controller
    {
        private UpackContext _db;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IHostEnvironment _environment;
        private readonly FileUploadService _uploadService;
        private ILogger<AccountController> _iLogger;
        Logger _nLogger = LogManager.GetCurrentClassLogger();

        public ApplicationsController(UpackContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager, SignInManager<User> signInManager, IHostEnvironment environment, FileUploadService uploadService, ILogger<AccountController> iLogger)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _environment = environment;
            _uploadService = uploadService;
            _iLogger = iLogger;
        }
        
        /// <summary>
        /// Стартовая страница по отображению списком всех обращений
        /// </summary>
        /// <param name="page">выбраный пользователем номер страницы на странице</param>
        /// <param name="userId">id пользователя, необходим для фильтрации списка обращений созданных данным пользователем</param>
        /// <param name="sort">способ сортировки</param>
        /// <returns>возвращает отсортирований список обращений</returns>
        [HttpGet]
        public IActionResult Index(int? page, string userId, AppSort sort = AppSort.NumApplDesc)
        {
            try
            {
                List<Application> applications = GetSortApplications(sort, userId);
                int pageSize = 13;
                int pageNumber = page ?? 1;
                return View(applications.ToPagedList(pageNumber, pageSize));
                
            }
            catch (Exception e)
            {
                _nLogger.Error($"Внимание ошибка: {e.Message} => {e.StackTrace}");
                return NotFound();
            }
        }

        /// <summary>
        /// Экшн по предварительному созданию нового обращения
        /// </summary>
        /// <returns>возвращает предварительную страницу создания нового обращения</returns>
        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                ApplViewModel model = new ApplViewModel();
                return View(model);
            }
            catch (Exception e)
            {
                _nLogger.Error($"Внимание ошибка: {e.Message} | {e.StackTrace}");
                return NotFound();
            }
        }
        
        /// <summary>
        /// Экшн для создания нового обращения
        /// </summary>
        /// <param name="model">контейнер с данными со страницы</param>
        /// <returns>в случае положительного результата при создании нового обращения, пользователь будет перенапрвлен на стартовую страницу, в список всех обращений</returns>
        [HttpPost]
        public async Task<IActionResult> Create(ApplViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User manager = await _userManager.FindByEmailAsync(User.Identity.Name);
                    if (manager != null)
                    {
                        Client client = _db.Clients.FirstOrDefault(c => c.CodeClient.ToUpper() == model.CodeClient.ToUpper());
                        CheckClient(manager, client, model); 
                        return RedirectToAction("Index");
                    }
                    return Content("Не найден менеджер");
                } 
                return View(model);
            }
            catch (Exception e)
            {
                _nLogger.Error($"Внимание ошибка: {e.Message} | {e.StackTrace}");
                return NotFound();
            }
        }

        /// <summary>
        /// Экшн по предварительному редактированию существующего обращения
        /// </summary>
        /// <param name="id">id для поиска нужного обращения</param>
        /// <returns>возвращает предварительную страницу редактирования нового обращения</returns>
        [HttpGet]
        public IActionResult Edit(string id)
        {
            try
            {
                if (id != null)
                {
                    Application appl = _db.Applications.FirstOrDefault(a => a.Id == id);
                    if (appl != null)
                    {
                        ApplViewModel model = new ApplViewModel()
                        {
                            CodeClient = appl.Client.CodeClient,
                            NameClient = appl.Client.Title,
                            ArticleNumber = appl.ArticleNumber,
                            Quantity = (int)appl.Quantity,
                            Price = appl.Price,
                            Comment = appl.Comment
                        };
                        ViewBag.ApplId = appl.Id;
                        ViewBag.StateAppl = appl.AppState;
                        return View(model);
                    }
                    return Content("Не найдено обращение");
                }
                return Content("Неверный Id");
            }
            catch (Exception e)
            {
                _nLogger.Error($"Внимание ошибка: {e.Message} | {e.StackTrace}");
                return NotFound();
            }
        }

        /// <summary>
        /// Экшн по редактированию существующего обращения.
        /// </summary>
        /// <param name="model">контейнер с данными</param>
        /// <param name="applId">id обращения, вынесен отдельно из контейнера model из-за валидации</param>
        /// <returns>в случае положительного обновления обращения, пользователь будет перенаправлен на стартовую страницу всех обращений.</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(ApplViewModel model, string applId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Application appl = _db.Applications.FirstOrDefault(ap => ap.Id == applId);
                    if (appl != null)
                    {
                        Client client = await _db.Clients.FirstOrDefaultAsync(c => c.CodeClient.ToUpper() == model.CodeClient.ToUpper());
                        if (client != null)
                        {
                            UpdateApplication(appl, client, model);
                            return RedirectToAction("Index");
                        }
                        
                        Client newClient = new Client() {CodeClient = model.CodeClient.ToUpper(), Title = model.NameClient};
                        _db.Clients.Add(newClient);
                        await _db.SaveChangesAsync();

                        UpdateApplication(appl, newClient, model);
                        return RedirectToAction("Index");
                    }

                    return Content("Обращение не найдено");

                }

                ViewBag.ApplId = applId;
                return View(model);
            }
            catch (Exception e)
            {
                _nLogger.Error($"Внимание ошибка: {e.Message} | {e.StackTrace}");
                return NotFound();
            }
        }

        /// <summary>
        /// Экшн для изменения даты ожидания и смене статуса обращения
        /// </summary>
        /// <param name="applId">id обращения</param>
        /// <param name="date">указанная дата пользователем на странице</param>
        /// <param name="comment">оставленный комментарий</param>
        /// <param name="state">передаваемый статус</param>
        /// <returns>в случае положительного обновления обращения, пользователь будет перенапровлен на стартовую страницу всех обращений</returns>
        [HttpPost]
        public IActionResult ChangeDateWaite(string applId, DateTime date, string comment, string state)
        {
            try
            {
                if (applId != null)
                {
                    Application appl = _db.Applications.FirstOrDefault(a => a.Id == applId);
                    if (appl != null)
                    {
                        switch (state)
                        {
                            case "Новая":
                                appl.AppState = AppState.Ожидается;
                                break;
                            
                            case "Ожидается":
                                appl.AppState = AppState.Закрыта;
                                break;
                            
                            case "Закрыта":
                                return Content("Данное обращение было успешно закрыто");
                        }
                        
                        appl.WaitingDate = date;
                        appl.Comment = comment;
                        
                        _db.Applications.Update(appl);
                        _db.SaveChanges();
                        
                        return RedirectToAction("Index");
                    }
                    

CRM_Upack_kz/Views/Applications/ConfirmDelete.cshtml
@model Application

@{
    ViewBag.Title = "Удаление обращения";
    Layout = "_Layout";
}

<div class="text-center col-sm-3 col-md-3 col-lg-12">
    <form method="post" asp-action="Delete" asp-controller="Applications" asp-route-id="@Model.Id">
        <div class="text-center col-sm-3 col-md-3 col-lg-12">
            <table class="table table-hover">
                <thead class="table-light">
                    <tr>
                      <th scope="col" class="font">Менеджер</th>
                      <th scope="col" class="font">Дата создания</th>
                      <th scope="col" class="font">Ожидается</th>
                      <th scope="col" class="font">Код клиента</th>
                      <th scope="col" class="font">Клиент</th>
                      <th scope="col" class="font">Артикул</th>
                      <th scope="col" class="font">Кол-во</th>
                      <th scope="col" class="font">Цена</th>
                      <th scope="col" class="font">Сумма</th>
                      <th scope="col" class="font">Комментарий</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="font text-dark">@Model.Manager.Surname @Model.Manager.Name</td>
                        <td class="font text-dark">@Model.CreateDate.ToShortDateString()</td>
                        <td class="font text-danger">
                            @if (Model.WaitingDate != new DateTime(0001, 01, 01))
                            {
                                @Model.WaitingDate.ToShortDateString()
                            }
                            else
                            {
                                @:Дата не указана
                            }
                        </td>
                        <td class="font text-dark">@Model.Client.CodeClient</td>
                        <td class="font text-dark">@Model.Client.Title</td>
                        <td class="font text-dark">@Model.ArticleNumber</td>
                        <td class="font text-dark">@Model.Quantity</td>
                        <td class="font text-dark">@Model.Price</td>
                        <td class="font text-dark">@Model.Amount</td>
                        <td class="font text-dark">@Model.Comment</td>
                    </tr>
                </tbody>
              </table>
            </div>
        <input class="btn btn-danger"  type="submit" value="Да">
        <a class="btn btn-success" asp-action="Index" asp-controller="Applications">Нет</a>
    </form>
</div>

@section Scripts
{
    <script >
    $(document).ready(function () {
        $('#caption').text("Удаление обращения");
    });
    
  
 </script>
}

CRM_Upack_kz/Views/Applications/Create.cshtml
@model CRM_Upack_kz.ViewModels.ApplViewModel

@{
    Layout = "_Layout";
}
<div id="BaseBody" class="text-center col col-sm-3 col-md-4 col-lg-12"></div>
<div class="baseElement col-md-4 pt-3 pb-4 ">
    <h4>Заполните поля</h4>
    <form asp-action="Create" asp-controller="Applications" method="post" enctype="multipart/form-data">
        @{
            Html.RenderPartial("PartialViews/ApplicationFormPartial", @Model);
        }
        <div>
            <input type="submit" id="edit" class="btn btn-outline-primary shadow-sm" value="Создать">
        </div>
    </form>
</div>



@section Scripts
{
    <script >
    $(document).ready(function () {
        $('#caption').text("Добавьте новое обращение");
    });
    
        
    function GetInfoClientAjax(){
        var codeClient = $('#codeClient').val();
                
        $.ajax({
            url : '@Url.Action("GetInfoClientAjax", "Applications")',
            type : 'GET',
            data : {
                'codeClient' : codeClient
            },
            success : function (data){
                if (data === "Клиент не найден, заполните клиента") {
                   $('#nameClient').val('');
                   $('#nameClient').attr('placeholder', data);
                   $('#nameClient').attr('disabled', false);
                   $('#hiddenClient').val('');
                }
                else {
                    $('#nameClient').val(data); 
                    $('#nameClient').attr('disabled', true);
                    $('#hiddenClient').val(data);
                }
            }
        });
    }
 </script>
}

CRM_Upack_kz/Views/Applications/Edit.cshtml
@using CRM_Upack_kz.Enums
@model CRM_Upack_kz.ViewModels.ApplViewModel

@{
    Layout = "_Layout";
}

<div id="BaseBody" class="text-center col col-sm-3 col-md-4 col-lg-12"></div>
@if (ViewBag.StateAppl == AppState.Закрыта)
{
    <div class="baseElement col-md-4 pt-3 pb-4 ">
        <h4>Данное обращение было закрыто</h4>
    </div>
}
else if (ViewBag.StateAppl == AppState.Ожидается)
{
    <div class="baseElement card mb-3" style="max-width: 540px;">
      <div class="row g-0 shadow">
        <div class="col-md-4">
          <img src="..\..\/Images/Warning/warning.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Внимание!</h5>
            <p class="card-text">Данное обращение редатировать запрещено.</p>
            <p class="card-text"><small class="text-muted">Последнее обновление 3 минуты назад</small></p>
          </div>
        </div>
      </div>
    </div>
}
else
{
    <div class="baseElement col-md-4 pt-3 pb-4 ">
        <h4>Заполните поля</h4>
        <form asp-action="Edit" asp-controller="Applications" method="post" asp-route-applId="@ViewBag.ApplId" enctype="multipart/form-data">
            @{
                Html.RenderPartial("PartialViews/ApplicationFormPartial");
            }
            <div>
                <input type="submit" id="edit" class="btn btn-outline-primary shadow-sm" value="Изменить">
            </div>
        </form>
    </div>
}

@section Scripts
{
    <script >
    $(document).ready(function () {
        $('#caption').text("Измените обращение");
    });
    
    function GetInfoClientAjax(){
        var codeClient = $('#codeClient').val();
                
        $.ajax({
            url : '@Url.Action("GetInfoClientAjax", "Applications")',
            type : 'GET',
            data : {
                'codeClient' : codeClient
            },
            success : function (data){
                if (data === "Клиент не найден, заполните клиента") {
                   $('#nameClient').attr('disabled', false);
                }
                else {
                    $('#nameClient').val(data); 
                    $('#nameClient').attr('disabled', true);
                }
            }
        });
    }
 </script>
}

CRM_Upack_kz/Views/Applications/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Bootstrap4.Core
@using CRM_Upack_kz.Enums
@inject UpackContext _db
@model X.PagedList.IPagedList<Application>


@{
    ViewBag.Title = "Список обращений";
    Layout = "_Layout";
}

@{
  if (Model.Count != 0)
  {
    
    <div id="BaseBody" class="text-center col col-sm-3 col-md-4 col-lg-12"></div>

    <div class="baseElement text-center col col-sm-3 col-md-4 col-lg-12">
      <table class="table table-hover">
        <thead class="table-light">
        <tr>
          <th scope="col" class="font"><a class="" asp-action="Index" asp-route-sort="@ViewBag.NumAppl"><span class="badge bg-info">№</span></a></th>
          <th scope="col" class="font"><a class=""  asp-action="Index" asp-route-sort="@ViewBag.Manager"><span class="badge bg-secondary">Менеджер</span></a></th>
          <th scope="col" class="font"><a class=""  asp-action="Index" asp-route-sort="@ViewBag.CreateDate"><span class="badge bg-secondary">Дата создания</span></a></th>
          <th scope="col" class="font">Ожидается</th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.CodeClient"><span class="badge bg-secondary">Код клиента</span></a></th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.NameClient"><span class="badge bg-secondary">Клиент</span></a></th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.ArtNum"><span class="badge bg-secondary">Артикул</span></a></th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.Quntity"><span class="badge bg-secondary">Кол-во</span></a></th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.Price"><span class="badge bg-secondary">Цена</span></a></th>
          <th scope="col" class="font"><a asp-action="Index" asp-route-sort="@ViewBag.Amount"><span class="badge bg-secondary">Сумма</span></a></th>
          <th scope="col" class="font">Комментарий</th>
          <th scope="col" class="font">Действия</th>
        </tr>
        </thead>
        <tbody>
        @{ 
          foreach (var appl in Model)
          {
            <tr>
              <td class="font text-dark"><b>@appl.NumberApplication</b></td>
              <td class="font text-dark">@appl.Manager.Surname @appl.Manager.Name</td>
              <td class="font text-dark">@appl.CreateDate.ToShortDateString() @appl.CreateDate.ToShortTimeString()</td>
              <td class="font @if(appl.WaitingDate != new DateTime(0001, 01, 01)) 
                              {
                                @:text-success
                              } 
                              else
                              { 
                                @:text-danger
                              }
                             ">
                @if (appl.WaitingDate != new DateTime(0001, 01, 01))
                {
                  <b>@appl.WaitingDate.ToShortDateString()</b>
                }
                else
                {
                  @:Дата не указана
                }
              </td>
              <td class="font text-dark">@appl.Client.CodeClient</td>
              <td class="font text-dark">@appl.Client.Title</td>
              <td class="font text-dark">@appl.ArticleNumber</td>
              <td class="font text-dark">@appl.Quantity</td>
              <td class="font text-dark">@appl.Price</td>
              <td class="font text-dark">@appl.Amount</td>
              <td class="font text-dark">@appl.Comment</td>
              <td>
                <div class="btn-group btn-group-sm shadow" role="group" aria-label="Button group with nested dropdown">
                  @if (appl.AppState == AppState.Новая & (User.Identity.Name == appl.Manager.Email || User.IsInRole("admin") || User.IsInRole("merch")))
                  {
                    if (User.IsInRole("admin") || User.IsInRole("merch"))
                    {
                      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#calendar" data-bs-whatever="@appl.Id" title="Ответить" onclick="check('@appl.Id', '@appl.CreateDate.Year', '@appl.CreateDate.Month', '@appl.CreateDate.Day', '@appl.AppState')">Ответить</button>
                    }
                    if (User.IsInRole("admin") || User.Identity.Name == appl.Manager.Email)
                    {
                      <a class="btn btn-sm btn-warning pt-2" title="Редактировать" asp-route-id="@appl.Id" asp-action="Edit" asp-controller="Applications"><i class="bi bi-pencil-square"></i></a>
                      <a class="btn btn-sm btn-danger pt-2" title="Удалить" asp-route-id="@appl.Id" asp-action="ConfirmDelete" asp-controller="Applications"><i class="bi bi-trash"></i></a>
                    }
                  }

                  else if (appl.AppState == AppState.Ожидается & (User.Identity.Name == appl.Manager.Email || User.IsInRole("admin") || User.IsInRole("merch")))
                  {
                    if (User.IsInRole("admin") || User.IsInRole("merch"))
                    {
                      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#calendar" data-bs-whatever="@appl.Id" title="Проверить" onclick="checkWaiteDate('@appl.Id', '@appl.CreateDate.Year', '@appl.CreateDate.Month', '@appl.CreateDate.Day', '@appl.WaitingDate.Year', '@appl.WaitingDate.Month', '@appl.WaitingDate.Day', '@appl.WaitingDate.ToShortTimeString()', '@appl.Comment', '@appl.AppState')">Проверить</button>
                      @if (User.IsInRole("admin"))
                      {
                        <a class="btn btn-sm btn-warning pt-2" title="Редактировать" asp-route-id="@appl.Id" asp-action="Edit" asp-controller="Applications"><i class="bi bi-pencil-square"></i></a>
                        <a class="btn btn-sm btn-danger pt-2" title="Удалить" asp-route-id="@appl.Id" asp-action="ConfirmDelete" asp-controller="Applications"><i class="bi bi-trash"></i></a>
                      }
                    }
                  }

                  else if (appl.AppState == AppState.Закрыта & User.IsInRole("admin"))
                  {
                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#calendar" data-bs-whatever="@appl.Id" title="Ответить" onclick="check('@appl.Id', '@appl.CreateDate.Year', '@appl.CreateDate.Month', '@appl.CreateDate.Day', '@appl.AppState')">Ответить</button>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#calendar" data-bs-whatever="@appl.Id" title="Проверить" onclick="checkWaiteDate('@appl.Id', '@appl.CreateDate.Year', '@appl.CreateDate.Month', '@appl.CreateDate.Day', '@appl.WaitingDate.Year', '@appl.WaitingDate.Month', '@appl.WaitingDate.Day', '@appl.WaitingDate.ToShortTimeString()', '@appl.Comment', '@appl.AppState')">Проверить</button>
                    <a class="btn btn-sm btn-warning pt-2" title="Редактировать" asp-route-id="@appl.Id" asp-action="Edit" asp-controller="Applications"><i class="bi bi-pencil-square"></i></a>
                    <a class="btn btn-sm btn-danger pt-2" title="Удалить" asp-route-id="@appl.Id" asp-action="ConfirmDelete" asp-controller="Applications"><i class="bi bi-trash"></i></a>
                  }
                  
                  else if (appl.AppState == AppState.Закрыта)
                  {
                    <button type="button" class="btn btn-outline-success" disabled>Закрыто</button>
                  }
                  
                </div>
              </td>
            </tr>
          }
        }
        </tbody>
      </table>
    </div>
    
    
    <p class="baseElement text-center">Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount всего обращений @_db.Applications.Count()</p>
    <div class="baseElement row justify-content-center col-md-6 col-lg-6">
      @Html.PagedListPager(Model, page => Url.Action("Index", "Applications", new { page, ViewBag.sort }), Bootstrap4PagedListRenderOptions.Default)
    </div>
    
    
    <div class="modal fade" id="calendar" tabindex="-1" aria-labelledby="calendarCaption" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="calendarCaption">Укажите дату ожидания</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button>
          </div>
          <div class="modal-body">
            <form asp-controller="Applications" asp-action="ChangeDateWaite" method="post">
              <div class="mb-3">
                <label id="dateWaite" for="date" class="col-form-label">Дата ожидания:</label>
                <input type="date" class="form-control" name="date" id="date" onchange="ValidationDate()">
                <input type="text" name="applId" value="" id="sendId" hidden="true">
                <input type="text" name="state" value="" id="applState" hidden="true">
                
                <input type="date" class="form-control" name="startDate" id="startDate" hidden="true">
                <input type="date" class="form-control" name="endDate" id="endDate" hidden="true">
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Комментарий:</label>
                <textarea class="form-control" id="message-text" name="comment"></textarea>
              </div>
              @if (User.IsInRole("admin") || User.IsInRole("merch"))
              {
                <input id="sendProduct" type="submit" class="btn btn-primary" value="Товар поступил">
              }
              <input id="sendCalendar" type="submit" class="btn btn-primary" value="Сохранить" disabled>
            </form>
          </div>
        </div>
      </div>
    </div>
    
  }
  else{<h3>Обращений не поступило, добавьте новые обращения</h3>}
}

@section Scripts
{
  <script >
    $(document).ready(function () {
        $('#caption').text("Список обращений");
        $('#applications').addClass("active");
        $('#users').removeClass("active");
    });
    
    let startDate = new Date();
    let endDate = new Date();
    let dateWaite = new Date();
    let _state = '';
    
    function ValidationDate(){
        
        dateWaite = new Date($('#date').val().substring(0,10));
        
                               
        if (startDate <= dateWaite && dateWaite <= endDate)
        {
          if (_state === 'Новая')
          {
            $('#sendCalendar').attr("hidden", false).removeAttr('disabled');
            $('#sendProduct').attr("hidden", true);
          }
          else if (_state === 'Ожидается')
          {
            $('#sendCalendar').attr("hidden", true);
            $('#sendProduct').attr("hidden", false).removeAttr('disabled'); 
          }
          
          $('#date, #dateWaite').removeClass("text-danger is-invalid");
          $('#date, #dateWaite').addClass("text-success is-valid");
            
          return true;
        }
        else 
        {
          $('#sendCalendar').attr('disabled', true);
          $('#sendProduct').attr("disabled", true);
          
          $('#date, #dateWaite').addClass("text-danger is-invalid");
          $('#date, #dateWaite').removeClass("text-success is-valid");
          
          return false;
        }
    }
    
    function check(applId, year, month, day, state){
      $('#sendCalendar').attr('disabled', true).attr('hidden', false);
      $('#sendProduct').attr("hidden", true);
      
      $('#date, #dateWaite').val('').removeClass("text-danger is-invalid text-success is-valid");
      $('#message-text').val('');
      $('#sendId').val(applId);
      $('#applState').val(state);
      _state = state;
      setDates(year, month, day);
    }
    
    function checkWaiteDate(applId, year, month, day, dWYear, dWMonth, dWDay,timeWaite, comment, state){
      $('#sendCalendar').attr('hidden', true);
      $('#sendProduct').attr('disabled', true).attr('hidden', false);
      
      $('#date').val(dWYear + "-" + checkNum(dWMonth) + "-" + checkNum(dWDay));
      $('#message-text').val(comment);
      $('#sendId').val(applId);
      $('#applState').val(state);
      _state = state;
      setDates(year, month, day);
      ValidationDate();
    }
    
    function setDates(year, month, day){
      if (month !== 0){
        month = month - 1;
      }
      startDate = new Date(year, month, day);
      endDate = new Date(startDate.getFullYear() + 1, month, day);
    }
    
    function checkNum(num){
      if (num < 10){
        num = "0" + num;
      }
      return num.toString();
    }
       
    
 </script>
}